---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-sa
  namespace: voting-app
  labels:
    app: vote
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result-sa
  namespace: voting-app
  labels:
    app: result
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: voting-app
  labels:
    app: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: voting-app
  labels:
    app: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: voting-app
  labels:
    app: redis
